# Generated by Django 2.0 on 2019-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_remove_img_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
